# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-12-09 13:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('instival_database', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='festival',
            name='date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
