# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-12-09 13:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instival_database', '0003_auto_20161209_1306'),
    ]

    operations = [
        migrations.AlterField(
            model_name='festival',
            name='date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='self_introduction',
            field=models.TextField(blank=True),
        ),
    ]
