# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-12-09 13:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instival_database', '0004_auto_20161209_1315'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='picture',
            field=models.URLField(null=True),
        ),
    ]
