# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-12-13 04:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('instival_database', '0005_post_picture'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='comment_id',
            new_name='comment_id_group',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='like_id',
            new_name='like_id_group',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='comment_id',
            new_name='comment_id_group',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='like_id',
            new_name='like_id_group',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='past_post',
            new_name='past_post_group',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='passward',
            new_name='password',
        ),
    ]
