# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-12-14 13:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('instival_database', '0006_auto_20161213_0425'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='post_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='instival_database.Post'),
        ),
    ]
