# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-12-21 08:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instival_database', '0010_auto_20161214_1803'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='picture',
            field=models.URLField(max_length=40000, null=True),
        ),
    ]
