# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-12-16 04:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('instival_database', '0011_auto_20161216_0421'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='post_id',
            new_name='post',
        ),
    ]
