# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-12-20 04:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('instival_database', '0011_auto_20161219_0905'),
        ('instival_database', '0012_auto_20161216_0425'),
    ]

    operations = [
    ]
