# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-12-23 11:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('instival_database', '0015_auto_20161222_1731'),
        ('instival_database', '0012_auto_20161221_0844'),
    ]

    operations = [
    ]
