# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-12-23 12:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('instival_database', '0016_merge'),
    ]

    operations = [
        migrations.CreateModel(
            name='Festival_Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('introduction', models.TextField(blank=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='festival',
            name='introduction',
        ),
        migrations.RemoveField(
            model_name='festival',
            name='location',
        ),
        migrations.AlterField(
            model_name='festival',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='post',
            name='festival_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='instival_database.Festival_Country'),
        ),
        migrations.AlterField(
            model_name='post',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='instival_database.Country'),
        ),
        migrations.AddField(
            model_name='festival_country',
            name='festival',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='instival_database.Festival'),
        ),
        migrations.AddField(
            model_name='festival_country',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='instival_database.Country'),
        ),
    ]
