# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-12-23 13:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('instival_database', '0017_auto_20161223_1247'),
    ]

    operations = [
        migrations.AddField(
            model_name='festival_country',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
