# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-12-23 15:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('instival_database', '0018_festival_country_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='festival_country',
            name='date',
        ),
    ]
