# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-12-27 02:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('instival_database', '0019_remove_festival_country_date'),
        ('instival_database', '0013_merge'),
    ]

    operations = [
    ]
