# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-01-06 09:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('instival_database', '0021_auto_20161228_0819'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profile_user', to='instival_database.User'),
        ),
    ]
