# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-01-06 15:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instival_database', '0024_auto_20170106_1027'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile_picture',
            field=models.URLField(blank=True),
        ),
    ]
